# Generated by Django 6.0.6 on 2026-06-28 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Denda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlahDenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alasanDenda', models.CharField(max_length=100)),
                ('statusBayar', models.CharField(max_length=20)),
                ('kembali', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namakategori', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='email',
            field=models.CharField(default='Raniah@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='password',
            field=models.CharField(default=246500, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='programstudi',
            field=models.CharField(default='Teknik Informatika', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('penerbit', models.CharField(max_length=50)),
                ('tahunterbit', models.IntegerField()),
                ('isbn', models.CharField(max_length=13)),
                ('statusBuku', models.CharField(max_length=10)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.CharField(max_length=200)),
                ('tanggalKirim', models.DateField()),
                ('statusBaca', models.CharField(max_length=20)),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggalPengembalian', models.DateField()),
                ('kondisiBuku', models.CharField(max_length=20)),
                ('statusPengembalian', models.CharField(max_length=20)),
                ('pinjam_id', models.CharField(max_length=30)),
                ('petugas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.petugas')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggalPinjam', models.DateField()),
                ('tanggalJatuhTempo', models.DateField()),
                ('jumlahPerpanjangan', models.IntegerField()),
                ('statusPinjam', models.CharField(max_length=10)),
                ('buku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.buku')),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mahasiswa')),
                ('petugas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.petugas')),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenisLaporan', models.CharField(max_length=50)),
                ('tanggalCetak', models.DateField()),
                ('petugas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.petugas')),
            ],
        ),
    ]
